CREATE TABLE IF NOT EXISTS "unit_workload_policies" ("id" serial PRIMARY KEY NOT NULL, "unit_id" integer NOT NULL, "version" integer DEFAULT 1 NOT NULL, "label" text DEFAULT 'Demo policy' NOT NULL, "night_start_hh" integer DEFAULT 22 NOT NULL, "night_end_hh" integer DEFAULT 6 NOT NULL, "warn_weekly_hours_exceeds" real DEFAULT 48, "warn_consecutive_days_exceeds" integer DEFAULT 6, "warn_night_shifts_per_month_exceeds" integer DEFAULT 8, "block_weekly_hours_exceeds" real DEFAULT 60, "block_consecutive_days_exceeds" integer DEFAULT 10, "min_recovery_hours_warning" real DEFAULT 10, "min_recovery_hours_block" real DEFAULT 8, "max_additional_hours_per_week" real DEFAULT 10, "is_active" boolean DEFAULT true NOT NULL, "is_demo_config" boolean DEFAULT true NOT NULL, "demo_config_note" text, "created_by" integer, "effective_from" timestamp DEFAULT now() NOT NULL, "effective_to" timestamp, "created_at" timestamp DEFAULT now() NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "skills" ("id" serial PRIMARY KEY NOT NULL, "name" text NOT NULL, "category" text, "description" text, "created_at" timestamp DEFAULT now() NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "personnel_skills" ("id" serial PRIMARY KEY NOT NULL, "user_id" integer NOT NULL, "skill_id" integer NOT NULL, "certified_at" timestamp, "expires_at" timestamp, "certified_by" integer, "created_at" timestamp DEFAULT now() NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "duty_ledger" ("id" serial PRIMARY KEY NOT NULL, "user_id" integer NOT NULL, "unit_id" integer NOT NULL, "duty_type" text DEFAULT 'general' NOT NULL, "scheduled_start" timestamp NOT NULL, "scheduled_end" timestamp NOT NULL, "scheduled_break_minutes" integer DEFAULT 0, "actual_start" timestamp, "actual_end" timestamp, "actual_break_minutes" integer, "actual_source" text, "verification_status" text DEFAULT 'pending' NOT NULL, "verified_by" integer, "verified_at" timestamp, "is_additional_duty" boolean DEFAULT false NOT NULL, "additional_duty_reason" text, "status" text DEFAULT 'scheduled' NOT NULL, "scheduled_duration_minutes" integer, "actual_duration_minutes" integer, "additional_minutes" integer DEFAULT 0, "night_duration_minutes" integer DEFAULT 0, "recovery_interval_minutes" integer, "has_overlap_flag" boolean DEFAULT false NOT NULL, "import_job_id" integer, "source_tag" text, "notes" text, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "duty_corrections" ("id" serial PRIMARY KEY NOT NULL, "duty_ledger_id" integer, "reported_by" integer NOT NULL, "unit_id" integer NOT NULL, "reported_actual_start" timestamp, "reported_actual_end" timestamp, "reported_break_minutes" integer, "is_unrecorded_duty" boolean DEFAULT false NOT NULL, "explanation" text NOT NULL, "status" text DEFAULT 'submitted' NOT NULL, "reviewed_by" integer, "reviewed_at" timestamp, "review_decision" text, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "assignments" ("id" serial PRIMARY KEY NOT NULL, "title" text NOT NULL, "description" text, "unit_id" integer NOT NULL, "assignee_id" integer, "required_skill_id" integer, "estimated_effort_hours" real, "planned_start" timestamp, "planned_end" timestamp, "deadline" timestamp, "priority" text DEFAULT 'normal' NOT NULL, "effort_type" text DEFAULT 'additional' NOT NULL, "linked_duty_ledger_id" integer, "status" text DEFAULT 'draft' NOT NULL, "assignment_reason" text, "created_by" integer NOT NULL, "approved_by" integer, "approved_at" timestamp, "capacity_check_result" jsonb, "override_reason" text, "overridden_by" integer, "overridden_at" timestamp, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "workload_review_requests" ("id" serial PRIMARY KEY NOT NULL, "requested_by" integer NOT NULL, "unit_id" integer NOT NULL, "reason" text NOT NULL, "explanation" text NOT NULL, "preferred_adjustment" text, "linked_duty_ledger_ids" integer[], "linked_assignment_ids" integer[], "visibility_acknowledged" boolean DEFAULT false NOT NULL, "visibility_note" text, "status" text DEFAULT 'submitted' NOT NULL, "acknowledged_by" integer, "acknowledged_at" timestamp, "reviewed_by" integer, "proposed_adjustment" text, "proposed_at" timestamp, "personnel_response" text, "personnel_responded_at" timestamp, "closure_note" text, "closed_at" timestamp, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "rebalancing_scenarios" ("id" serial PRIMARY KEY NOT NULL, "unit_id" integer NOT NULL, "title" text NOT NULL, "description" text, "period_start" timestamp NOT NULL, "period_end" timestamp NOT NULL, "status" text DEFAULT 'draft' NOT NULL, "created_by" integer NOT NULL, "reviewed_by" integer, "approved_by" integer, "approved_at" timestamp, "applied_at" timestamp, "applied_by" integer, "feasibility_result" jsonb, "change_summary" jsonb, "proposed_changes" jsonb, "disclaimer" text NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "duty_manager_access" ("id" serial PRIMARY KEY NOT NULL, "user_id" integer NOT NULL, "unit_id" integer NOT NULL, "can_view_individual_duty" boolean DEFAULT true NOT NULL, "can_edit_roster" boolean DEFAULT false NOT NULL, "can_approve_assignments" boolean DEFAULT false NOT NULL, "can_apply_scenarios" boolean DEFAULT false NOT NULL, "granted_by" integer NOT NULL, "granted_at" timestamp DEFAULT now() NOT NULL, "revoked_at" timestamp, "is_active" boolean DEFAULT true NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL);--> statement-breakpoint
ALTER TABLE "unit_workload_policies" ADD CONSTRAINT "unit_workload_policies_unit_id_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."units"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "unit_workload_policies" ADD CONSTRAINT "unit_workload_policies_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "personnel_skills" ADD CONSTRAINT "personnel_skills_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "personnel_skills" ADD CONSTRAINT "personnel_skills_skill_id_skills_id_fk" FOREIGN KEY ("skill_id") REFERENCES "public"."skills"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "personnel_skills" ADD CONSTRAINT "personnel_skills_certified_by_users_id_fk" FOREIGN KEY ("certified_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "duty_ledger" ADD CONSTRAINT "duty_ledger_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "duty_ledger" ADD CONSTRAINT "duty_ledger_unit_id_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."units"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "duty_ledger" ADD CONSTRAINT "duty_ledger_verified_by_users_id_fk" FOREIGN KEY ("verified_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "duty_corrections" ADD CONSTRAINT "duty_corrections_duty_ledger_id_duty_ledger_id_fk" FOREIGN KEY ("duty_ledger_id") REFERENCES "public"."duty_ledger"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "duty_corrections" ADD CONSTRAINT "duty_corrections_reported_by_users_id_fk" FOREIGN KEY ("reported_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "duty_corrections" ADD CONSTRAINT "duty_corrections_unit_id_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."units"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "duty_corrections" ADD CONSTRAINT "duty_corrections_reviewed_by_users_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assignments" ADD CONSTRAINT "assignments_unit_id_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."units"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assignments" ADD CONSTRAINT "assignments_assignee_id_users_id_fk" FOREIGN KEY ("assignee_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assignments" ADD CONSTRAINT "assignments_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workload_review_requests" ADD CONSTRAINT "workload_review_requests_requested_by_users_id_fk" FOREIGN KEY ("requested_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workload_review_requests" ADD CONSTRAINT "workload_review_requests_unit_id_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."units"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rebalancing_scenarios" ADD CONSTRAINT "rebalancing_scenarios_unit_id_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."units"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rebalancing_scenarios" ADD CONSTRAINT "rebalancing_scenarios_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "duty_manager_access" ADD CONSTRAINT "duty_manager_access_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "duty_manager_access" ADD CONSTRAINT "duty_manager_access_unit_id_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."units"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "duty_manager_access" ADD CONSTRAINT "duty_manager_access_granted_by_users_id_fk" FOREIGN KEY ("granted_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "skills_name_unique" ON "skills" USING btree ("name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "policy_unit_idx" ON "unit_workload_policies" USING btree ("unit_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ps_user_idx" ON "personnel_skills" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ps_user_skill_idx" ON "personnel_skills" USING btree ("user_id","skill_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ledger_user_idx" ON "duty_ledger" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ledger_unit_idx" ON "duty_ledger" USING btree ("unit_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ledger_scheduled_start_idx" ON "duty_ledger" USING btree ("scheduled_start");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "ledger_source_tag_idx" ON "duty_ledger" USING btree ("source_tag");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "correction_reporter_idx" ON "duty_corrections" USING btree ("reported_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "assign_unit_idx" ON "assignments" USING btree ("unit_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "assign_assignee_idx" ON "assignments" USING btree ("assignee_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "wlr_requester_idx" ON "workload_review_requests" USING btree ("requested_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "wlr_unit_idx" ON "workload_review_requests" USING btree ("unit_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "scenario_unit_idx" ON "rebalancing_scenarios" USING btree ("unit_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "dma_user_idx" ON "duty_manager_access" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "dma_user_unit_idx" ON "duty_manager_access" USING btree ("user_id","unit_id");
