CREATE TABLE IF NOT EXISTS "checkin_analyses" ("id" serial PRIMARY KEY NOT NULL, "checkin_id" integer NOT NULL UNIQUE, "user_id" integer NOT NULL, "assessment_id" integer, "summary" text NOT NULL, "summary_source" text DEFAULT 'template' NOT NULL, "observations" jsonb DEFAULT '[]' NOT NULL, "trend_summary" jsonb, "suggested_actions" jsonb DEFAULT '[]' NOT NULL, "follow_up_questions" jsonb DEFAULT '[]' NOT NULL, "follow_up_answers" jsonb DEFAULT '[]' NOT NULL, "revised_summary" text, "revised_at" timestamp, "missing_context" text[], "invalidated_at" timestamp, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "checkin_conversations" ("id" serial PRIMARY KEY NOT NULL, "checkin_id" integer NOT NULL, "user_id" integer NOT NULL, "role" text NOT NULL, "content" text NOT NULL, "source" text, "created_at" timestamp DEFAULT now() NOT NULL);--> statement-breakpoint
ALTER TABLE "checkin_analyses" ADD CONSTRAINT "checkin_analyses_checkin_id_check_ins_id_fk" FOREIGN KEY ("checkin_id") REFERENCES "public"."check_ins"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "checkin_analyses" ADD CONSTRAINT "checkin_analyses_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "checkin_analyses" ADD CONSTRAINT "checkin_analyses_assessment_id_assessments_id_fk" FOREIGN KEY ("assessment_id") REFERENCES "public"."assessments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "checkin_conversations" ADD CONSTRAINT "checkin_conversations_checkin_id_check_ins_id_fk" FOREIGN KEY ("checkin_id") REFERENCES "public"."check_ins"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "checkin_conversations" ADD CONSTRAINT "checkin_conversations_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cia_user_idx" ON "checkin_analyses" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cia_checkin_idx" ON "checkin_analyses" USING btree ("checkin_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "conv_checkin_idx" ON "checkin_conversations" USING btree ("checkin_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "conv_user_idx" ON "checkin_conversations" USING btree ("user_id");
